name: AUnit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: |
        cd ..
        git clone https://github.com/bxparks/AUnit
        git clone https://github.com/bxparks/EpoxyDuino

    - name: Verify tests
      run: |
        make -C tests tests
        make -C tests runtests
